BUGFIX/MAJOR(repository): Remove exclusion of zeromq from EPEL
 ##### SUMMARY

Currently, the installation is broken.
```
failed: [node1] (item=openio-sds-server) => changed=false
  attempts: 5
  msg: |-
    Error: Package: python2-zmq-14.7.0-8.el7.x86_64 (epel)
               Requires: libzmq.so.5()(64bit)
```

The new package changes the dependency
https://github.com/open-io/rpm-specfiles/pull/198

 ##### IMPACT
N/A

 ##### ADDITIONAL INFORMATION